--------------------------------------------------------------------------------
-- UNIFIED HYPRLAND CONFIG
--------------------------------------------------------------------------------

hl.config({ autogenerated = false })

------------------
---- MONITORS ----
------------------

hl.monitor({
    output   = "DP-3",
    disabled = false,
    mode     = "2560x1440@240.00Hz",
    position = "0x0",
    scale    = 1,
    cm       = "srgb",
})

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

---------------------
---- MY PROGRAMS ----
---------------------

local terminal    = "ghostty"
local fileManager = "nautilus"
local menu        = "qs ipc call launcher toggle"
local browser     = "helium"

-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 24")
    hl.exec_cmd("qs")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("HYPRCURSOR_SIZE", "24")

-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
    cursor = {
        enable_hyprcursor = true,
    },

    ecosystem = {
        no_donation_nag = true,
        no_update_news  = true,
    },

    general = {
        gaps_in     = 4,
        gaps_out    = 10,
        border_size = 1,

        col = {
            active_border   = { colors = {"rgba(ffffff55)", "rgba(ffffff22)"}, angle = 45 },
            inactive_border = "rgba(ffffff15)",
        },

        resize_on_border = false,
        allow_tearing    = false,
        layout           = "dwindle",
        snap = {
            enabled = false,
        },
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        active_opacity   = 0.88,
        inactive_opacity = 0.75,

        shadow = {
            enabled      = true,
            range        = 25,
            render_power = 4,
            color        = 0x55000000,
        },

        blur = {
            enabled   = true,
            size      = 8,
            passes    = 3,
            vibrancy  = 0.25,
            popups    = true,
        },
    },

    animations = {
        enabled = true,
    },

    misc = {
        force_default_wallpaper = -1,
        disable_hyprland_logo   = true,
    },
})

--------------------
---- ANIMATIONS ----
--------------------

hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1.0},  {0.32, 1.0} } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1.0} } })
hl.curve("linear",         { type = "bezier", points = { {0.0, 0.0},   {1.0, 1.0} } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1.0} } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0.0},  {0.1, 1.0} } })
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global",        enabled = true, speed = 10.0, bezier = "almostLinear" })
hl.animation({ leaf = "windowsMove",   enabled = true, speed = 2.0,  bezier = "quick" })
hl.animation({ leaf = "border",        enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true, speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 2.1,  bezier = "quick", style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 4.0,  bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 5.0,  bezier = "easeOutQuint", style = "slide" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 5.0,  bezier = "easeOutQuint", style = "slide" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 5.0,  bezier = "easeOutQuint", style = "slide" })
hl.animation({ leaf = "zoomFactor",    enabled = true, speed = 7.0,  bezier = "quick" })

-----------------
---- LAYOUTS ----
-----------------

hl.config({
    dwindle = {
        preserve_split = true,
    },
    master = {
        new_status = "master",
    },
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout    = "us,ua",
        kb_variant   = "",
        kb_model     = "",
        kb_options   = "grp:win_space_toggle",
        kb_rules     = "",
        follow_mouse = 1,
        sensitivity  = -0.1,

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers   = 3,
    direction = "horizontal",
    action    = "workspace",
})

hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})

---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER"

-- Applications & Utilities
hl.bind(mainMod .. " + Q",                hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + Return",           hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + SHIFT + Return",   hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + E",                hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + R",                hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + C",                hl.dsp.window.close())
hl.bind(mainMod .. " + M",                hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + V",                hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + P",                hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J",                hl.dsp.layout("togglesplit"))

-- Focus navigation (Super + Arrows / HJKL)
hl.bind(mainMod .. " + left",             hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right",            hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",               hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",             hl.dsp.focus({ direction = "down" }))

-- Window movement (Super + Shift + Arrows)
hl.bind(mainMod .. " + SHIFT + left",     hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + right",    hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + up",       hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + down",     hl.dsp.window.move({ direction = "down" }))

-- Window movement (Super + Shift + HJKL)
hl.bind(mainMod .. " + SHIFT + H",        hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + L",        hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + K",        hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + J",        hl.dsp.window.move({ direction = "down" }))

-- Workspaces
for i = 1, 10 do
    local key = i % 10
    hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Special workspace (scratchpad)
hl.bind(mainMod .. " + S",                hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S",        hl.dsp.window.move({ workspace = "special:magic" }))

-- Mouse bindings
hl.bind(mainMod .. " + mouse_down",       hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",         hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + mouse:272",        hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273",        hl.dsp.window.resize(), { mouse = true })

-- Media & Brightness keys
hl.bind("XF86AudioRaiseVolume",           hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume",           hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",                  hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",               hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",            hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",          hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

hl.bind("XF86AudioNext",                  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause",                 hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",                  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",                  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

----------------------
---- WINDOW RULES ----
----------------------

hl.window_rule({
    name           = "suppress-maximize-events",
    match          = { class = ".*" },
    suppress_event = "maximize",
})

hl.window_rule({
    name       = "fix-xwayland-drags",
    match      = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },
    no_focus   = true,
})

hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },
    move  = "20 monitor_h-120",
    float = true,
})
